// frontend/src/components/ProbabilityPlot.vue
<template>
  <div class="plots-wrapper" data-testid="probability-plots">
    <!-- Distribution Chart -->
    <div class="chart-container">
      <h3 class="chart-title">Successful Pull Distribution</h3>
      <div class="chart-canvas-container">
        <Line
          v-if="chartData"
          :key="chartData?.labels?.length ?? 0"
          :data="distributionChartData"
          :options="distributionChartOptions"
        />
      </div>
    </div>

    <!-- Cumulative Chart -->
    <div class="chart-container">
      <h3 class="chart-title">Cumulative Probability</h3>
      <div class="chart-canvas-container">
        <Line
          v-if="chartData"
          :key="chartData?.labels?.length ?? 0"
          :data="cumulativeChartData"
          :options="cumulativeChartOptions"
        />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import { Line } from 'vue-chartjs'
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend,
  ChartData,
  ChartOptions
} from 'chart.js'
import annotationPlugin from 'chartjs-plugin-annotation'

ChartJS.register(
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend,
  annotationPlugin
)

const props = defineProps<{
  bannerType: 'standard' | 'limited' | 'light_cone' | 'weapon' | 'w_engine'
  gameType: 'star_rail' | 'genshin' | 'zenless'
  currentPity: number
  plannedPulls: number
  result: {
    total_5_star_probability: number
  }
}>()

const visualizationData = ref<VisualizationData | null>(null)
const chartData = ref<ChartData | null>(null)

interface VisualizationData {
  rolls: number[];
  probability_per_roll: number[];
  cumulative_probability: number[];
  soft_pity_start: number;
  hard_pity: number;
  current_pity: number;
  planned_pulls: number;
}

async function fetchVisualizationData() {
  try {
    const response = await fetch('/api/visualization', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        game_type: props.gameType,
        banner_type: props.bannerType,
        current_pity: props.currentPity,
        planned_pulls: props.plannedPulls
      }),
    })

    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`)
    }

    const data = await response.json() as VisualizationData
    if (!Array.isArray(data.rolls) || !Array.isArray(data.probability_per_roll) || !Array.isArray(data.cumulative_probability)) {
      throw new Error('Invalid data format received')
    }

    visualizationData.value = data
    chartData.value = {
      labels: data.rolls,
      datasets: [
        {
          label: 'Probability Distribution',
          data: data.probability_per_roll.map(p => p * 100),
          borderColor: 'rgb(75, 192, 192)',
          tension: 0.1
        },
        {
          label: 'Cumulative Probability',
          data: data.cumulative_probability.map(p => p * 100),
          borderColor: 'rgb(153, 102, 255)',
          tension: 0.1
        }
      ]
    }
  } catch (error) {
    console.error('Error fetching visualization data:', error)
    // Set empty data on error
    chartData.value = {
      labels: [],
      datasets: [
        {
          label: 'Probability Distribution',
          data: [],
          borderColor: 'rgb(75, 192, 192)',
          tension: 0.1
        },
        {
          label: 'Cumulative Probability',
          data: [],
          borderColor: 'rgb(153, 102, 255)',
          tension: 0.1
        }
      ]
    }
  }
}

// Function to update charts
async function updateCharts() {
  try {
    await fetchVisualizationData()
  } catch (error) {
    console.error('Error fetching visualization data:', error)
  }
}

// Expose update function
defineExpose({ updateCharts })

const distributionChartData = computed<ChartData<'line'>>(() => ({
  labels: chartData.value?.labels ?? [],
  datasets: [{
    label: 'Pull Distribution',
    data: (chartData.value?.datasets[0].data ?? []) as number[],
    borderColor: 'rgb(75, 192, 192)',
    tension: 0.1,
    fill: false
  }]
}))

const cumulativeChartData = computed<ChartData<'line'>>(() => ({
  labels: chartData.value?.labels ?? [],
  datasets: [{
    label: 'Cumulative Probability',
    data: (chartData.value?.datasets[1].data ?? []) as number[],
    borderColor: 'rgb(153, 102, 255)',
    tension: 0.1,
    fill: false
  }]
}))

const chartAnnotations = computed(() => ({
  totalPulls: {
    type: 'line' as const,
    xMin: (visualizationData.value?.current_pity ?? 0) + (visualizationData.value?.planned_pulls ?? 0),
    xMax: (visualizationData.value?.current_pity ?? 0) + (visualizationData.value?.planned_pulls ?? 0),
    borderColor: 'rgba(255, 0, 0, 0.8)',
    borderWidth: 2,
    label: {
      content: `Total Pulls: ${(visualizationData.value?.current_pity ?? 0) + (visualizationData.value?.planned_pulls ?? 0)}`,
      display: true,
      backgroundColor: 'rgba(255, 255, 255, 0.8)',
      color: 'rgb(255, 0, 0)'
    }
  },
  softPity: {
    type: 'line' as const,
    xMin: visualizationData.value?.soft_pity_start ?? (props.bannerType === 'light_cone' ? 64 : 74),
    xMax: visualizationData.value?.soft_pity_start ?? (props.bannerType === 'light_cone' ? 64 : 74),
    borderColor: 'rgba(255, 165, 0, 0.5)',
    borderWidth: 2,
    borderDash: [5, 5],
    label: {
      content: 'Soft Pity',
      position: 'start' as const,
      display: true,
      backgroundColor: 'rgba(255, 255, 255, 0.8)',
      color: 'rgb(255, 165, 0)'
    }
  },
  hardPity: {
    type: 'line' as const,
    xMin: visualizationData.value?.hard_pity ?? 90,
    xMax: visualizationData.value?.hard_pity ?? 90,
    borderColor: 'rgba(255, 69, 0, 0.5)',
    borderWidth: 2,
    borderDash: [5, 5],
    label: {
      content: 'Hard Pity',
      display: true,
      backgroundColor: 'rgba(255, 255, 255, 0.8)',
      color: 'rgb(255, 69, 0)'
    }
  }
}))

const baseChartOptions = computed<ChartOptions<'line'>>(() => ({
  responsive: true,
  maintainAspectRatio: false,
  scales: {
    y: {
      beginAtZero: true,
      title: {
        display: true,
        text: 'Probability (%)'
      }
    },
    x: {
      title: {
        display: true,
        text: 'Number of Pulls'
      }
    }
  },
  plugins: {
    legend: {
      position: 'top'
    },
    annotation: {
      annotations: chartAnnotations.value
    }
  }
}))

const distributionChartOptions = computed<ChartOptions<'line'>>(() => ({
  ...baseChartOptions.value,
  plugins: {
    ...baseChartOptions.value.plugins,
    title: {
      display: true,
      text: 'Probability of getting 5★ at each pull'
    }
  }
}))

const cumulativeChartOptions = computed<ChartOptions<'line'>>(() => ({
  ...baseChartOptions.value,
  plugins: {
    ...baseChartOptions.value.plugins,
    title: {
      display: true,
      text: 'Cumulative probability of getting 5★'
    }
  }
}))
</script>

<style>
/* Styles moved to app.css */
</style>

// frontend/src/components/ProbabilityPlot.svelte
<script lang="ts">
  import {
    Chart,
    CategoryScale,
    LinearScale,
    PointElement,
    LineElement,
    LineController,
    Title,
    Tooltip,
    Legend,
    type ChartConfiguration,
    type InteractionModeMap
  } from 'chart.js';
  import annotationPlugin from 'chartjs-plugin-annotation';

  // Register required components
  Chart.register(
    CategoryScale,
    LinearScale,
    PointElement,
    LineElement,
    LineController,
    Title,
    Tooltip,
    Legend,
    annotationPlugin
  );
  
  export let bannerType: string;
  export let currentPity: number;
  export let plannedPulls: number;
  export let result: any;
  
  let cumulativeChartCanvas: HTMLCanvasElement;
  let distributionChartCanvas: HTMLCanvasElement;
  let cumulativeChart: Chart | null = null;
  let distributionChart: Chart | null = null;

  async function fetchVisualizationData() {
    try {
      console.log('Fetching visualization data for:', bannerType);
      const response = await fetch('/api/visualization', {
        method: 'POST',
        headers: { 
          'Content-Type': 'application/json',
          'Accept': 'application/json'
        },
        body: JSON.stringify({ 
          banner_type: bannerType, 
          current_pity: currentPity 
        })
      });

      console.log('Response status:', response.status);
      
      if (!response.ok) {
        const text = await response.text();
        console.error('API Error Response:', {
          status: response.status,
          statusText: response.statusText,
          body: text
        });
        throw new Error(`API error: ${response.status} ${response.statusText}`);
      }

      const text = await response.text();
      console.log('API Response:', text);
      
      try {
        return JSON.parse(text);
      } catch (e) {
        console.error('JSON Parse Error:', e);
        console.error('Invalid JSON:', text);
        throw new Error('Invalid JSON response from server');
      }
    } catch (error) {
      console.error('Visualization API error:', error);
      throw error;
    }
  }

  function createCharts(data: any) {
    const totalPulls = currentPity + plannedPulls;
    const maxProbIndex = data.probability_per_roll.indexOf(
      Math.max(...data.probability_per_roll)
    );
    const maxProbRoll = data.rolls[maxProbIndex];

    const commonScaleOptions = {
      x: {
        type: 'linear' as const,
        grid: {
          color: 'rgba(0, 0, 0, 0.1)'
        },
        border: {
          display: true,
          color: 'rgba(0, 0, 0, 0.1)'
        },
        title: {
          display: true,
          text: 'Roll Number'
        }
      }
    };

    const commonOptions = {
      responsive: true,
      maintainAspectRatio: false,
      interaction: {
        intersect: false,
        mode: 'index' as keyof InteractionModeMap
      }
    };

    // Cumulative Chart configuration
    const cumulativeConfig: ChartConfiguration<'line'> = {
      type: 'line',
      data: {
        labels: data.rolls,
        datasets: [{
          label: 'Cumulative Probability',
          data: data.cumulative_probability.map((p: number, i: number) => ({
            x: data.rolls[i],
            y: p * 100
          })),
          borderColor: 'rgb(220, 57, 18)',
          borderWidth: 2,
          tension: 0.4,
          fill: false,
          pointRadius: 0
        }]
      },
      options: {
        ...commonOptions,
        plugins: {
          legend: {
            display: true,
            position: 'top',
            labels: {
              font: { size: 10 },
              boxWidth: 15,
              padding: 10
            }
          },
          annotation: {
            annotations: {
              softPity: {
                type: 'line',
                xMin: data.soft_pity_start,
                xMax: data.soft_pity_start,
                borderColor: 'rgb(85, 168, 104)',
                borderWidth: 1.5,
                borderDash: [2, 2],
                label: {
                  content: `Soft Pity (${data.soft_pity_start})`,
                  display: true,
                  position: 'start',
                  yAdjust: -160,
                  backgroundColor: 'rgba(255, 255, 255, 0.9)',
                  color: 'rgb(85, 168, 104)',
                  font: { size: 11 },
                  padding: 4
                }
              },
              fiftyPercent: {
                type: 'line',
                yMin: 50,
                yMax: 50,
                borderColor: 'rgb(51, 102, 204)',
                borderWidth: 1.5,
                borderDash: [2, 2],
                label: {
                  content: '50% Chance',
                  display: true,
                  position: 'start',
                  backgroundColor: 'rgba(255, 255, 255, 0.9)',
                  color: 'rgb(51, 102, 204)',
                  font: { size: 11 },
                  padding: 4
                }
              },
              guarantee: {
                type: 'line',
                yMin: 100,
                yMax: 100,
                borderColor: 'rgb(46, 184, 92)',
                borderWidth: 1.5,
                borderDash: [4, 4],
                label: {
                  content: '100% Guarantee',
                  display: true,
                  position: 'start',
                  backgroundColor: 'rgba(255, 255, 255, 0.9)',
                  color: 'rgb(46, 184, 92)',
                  font: { size: 11 },
                  padding: 4
                }
              },
              hardPity: {
                type: 'line',
                xMin: data.hard_pity,
                xMax: data.hard_pity,
                borderColor: 'rgb(255, 127, 80)',
                borderWidth: 1.5,
                borderDash: [6, 6],
                label: {
                  content: `Hard Pity (${data.hard_pity})`,
                  display: true,
                  position: 'start',
                  backgroundColor: 'rgba(255, 255, 255, 0.9)',
                  color: 'rgb(255, 127, 80)',
                  font: { size: 11 },
                  padding: 4
                }
              },
              currentTotal: {
                type: 'line',
                xMin: totalPulls,
                xMax: totalPulls,
                borderColor: 'rgb(255, 0, 0)',
                borderWidth: 2,
                label: {
                  content: `Current Total (${totalPulls})`,
                  display: true,
                  position: 'start',
                  yAdjust: -30,
                  backgroundColor: 'rgba(255, 255, 255, 0.9)',
                  color: 'rgb(255, 0, 0)',
                  font: { size: 11 },
                  padding: 4
                }
              }
            }
          }
        },
        scales: {
          ...commonScaleOptions,
          y: {
            type: 'linear' as const,
            grid: {
              color: 'rgba(0, 0, 0, 0.1)'
            },
            title: {
              display: true,
              text: 'Cumulative Probability (%)'
            },
            min: 0,
            max: 100,
            ticks: {
              callback: function(tickValue: number | string): string {
                return typeof tickValue === 'number' ? tickValue.toFixed(2) : tickValue;
              }
            }
          }
        }
      }
    };

    // Distribution Chart configuration
    const distributionConfig: ChartConfiguration<'line'> = {
      type: 'line',
      data: {
        labels: data.rolls,
        datasets: [{
          label: 'Probability per Roll',
          data: data.probability_per_roll.map((p: number, i: number) => ({
            x: data.rolls[i],
            y: p * 100
          })),
          borderColor: 'rgb(76, 114, 176)',
          borderWidth: 2,
          tension: 0.4,
          fill: false,
          pointRadius: 0
        }]
      },
      options: {
        ...commonOptions,
        plugins: {
          legend: {
            display: true,
            position: 'top',
            labels: {
              font: { size: 10 },
              boxWidth: 15,
              padding: 10
            }
          },
          annotation: {
            annotations: {
              mostLikelyRoll: {
                type: 'line',
                xMin: maxProbRoll,
                xMax: maxProbRoll,
                borderColor: 'rgb(196, 78, 82)',
                borderWidth: 1.5,
                borderDash: [6, 6],
                label: {
                  content: `Most Likely Roll (${maxProbRoll})`,
                  display: true,
                  position: 'start',
                  backgroundColor: 'rgba(255, 255, 255, 0.9)',
                  color: 'rgb(196, 78, 82)',
                  font: { size: 11 },
                  padding: 4
                }
              },
              softPity: {
                type: 'line',
                xMin: data.soft_pity_start,
                xMax: data.soft_pity_start,
                borderColor: 'rgb(85, 168, 104)',
                borderWidth: 1.5,
                borderDash: [2, 2],
                label: {
                  content: `Soft Pity (${data.soft_pity_start})`,
                  display: true,
                  position: 'start',
                  yAdjust: -160,
                  backgroundColor: 'rgba(255, 255, 255, 0.9)',
                  color: 'rgb(85, 168, 104)',
                  font: { size: 11 },
                  padding: 4
                }
              },
              currentTotal: {
                type: 'line',
                xMin: totalPulls,
                xMax: totalPulls,
                borderColor: 'rgb(255, 0, 0)',
                borderWidth: 2,
                label: {
                  content: `Current Total (${totalPulls})`,
                  display: true,
                  position: 'start',
                  yAdjust: -30,
                  backgroundColor: 'rgba(255, 255, 255, 0.9)',
                  color: 'rgb(255, 0, 0)',
                  font: { size: 11 },
                  padding: 4
                }
              }
            }
          }
        },
        scales: {
          ...commonScaleOptions,
          y: {
            type: 'linear' as const,
            grid: {
              color: 'rgba(0, 0, 0, 0.1)'
            },
            title: {
              display: true,
              text: 'Probability per Roll (%)'
            },
            ticks: {
              callback: function(tickValue: number | string): string {
                return typeof tickValue === 'number' ? tickValue.toFixed(2) : tickValue;
              }
            }
          }
        }
      }
    };

    // Create new charts
    cumulativeChart = new Chart(cumulativeChartCanvas, cumulativeConfig);
    distributionChart = new Chart(distributionChartCanvas, distributionConfig);
  }

  async function updateCharts() {
    if (!distributionChartCanvas || !cumulativeChartCanvas) return;
    
    // Destroy existing charts
    if (distributionChart) {
      distributionChart.destroy();
      distributionChart = null;
    }
    if (cumulativeChart) {
      cumulativeChart.destroy();
      cumulativeChart = null;
    }
    
    try {
      const data = await fetchVisualizationData();
      createCharts(data);
    } catch (error) {
      console.error('Failed to update charts:', error);
    }
  }

  $: {
    if (result && distributionChartCanvas && cumulativeChartCanvas) {
      updateCharts();
    }
  }
</script>

<div class="chart-container">
  <div class="chart-wrapper">
    <h3 class="chart-title">
      Cumulative Probability
    </h3>
    <div class="chart-canvas-container">
      <canvas bind:this={cumulativeChartCanvas}></canvas>
    </div>
  </div>

  <div class="chart-wrapper">
    <h3 class="chart-title">
      Successful Pull Distribution
    </h3>
    <div class="chart-canvas-container">
      <canvas bind:this={distributionChartCanvas}></canvas>
    </div>
  </div>
</div>
